version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: study_work_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: study_work_db
    ports:
      - '5435:5432' # Cổng 5435 trên máy host tránh xung đột với cổng 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
